### ISSUE TITLE
Phantomas error

### ISSUE THREAD

**Issue by mig-25** [AvraamMavridis/gulp-louis#14]
I cloned your repo and did npm install. But after executing gulp, I get the following error:

```
MacBook-Pro-3:gulp-louis sohail$ gulp
(node:10780) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[09:50:52] Using gulpfile ~/GitHub/gulp-louis/gulp-louis/gulpfile.js
[09:50:52] Starting 'louis'...
[09:50:52] Finished 'louis' after 47 ms
[09:50:52] Starting 'default'...
[09:50:52] Finished 'default' after 12 μs
[09:50:52] Server started http://localhost:8888
{ Error: Command failed: phantoms http://localhost:8888 --engine webkit --runs 1 --timeout 60 --viewport 1280x1024 --reporter=json > results.json
/bin/sh: phantoms: command not found

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: 'phantoms http://localhost:8888 --engine webkit --runs 1 --timeout 60 --viewport 1280x1024 --reporter=json > results.json' }
```

What have I missed?

Thanks
-Sohail

**Comment by AvraamMavridis** [comment]
@mig-25 Hi, I will have a look later today. Maybe its a path issue.

**Comment by AvraamMavridis** [comment]
gulp updated to 2.0.0., please use that version. It should be fine.

**Comment by mig-25** [comment]
The version of gulp I am running is:

```
MacBook-Pro-3:page_speed sohail$ gulp -v
[15:12:05] CLI version 3.8.11
[15:12:05] Local version 3.9.1
```

So should I downgrade to gulp version 2.0.0?

**Comment by AvraamMavridis** [comment]
@mig-25 No, sorry, my mistake, I meant to use the new version of `gulp-louis` (2.0.0) . I just published a new version on `npm` that hopefully solves the issue. The problem with the previous version was that it required to have `phantomas` installed globally. With the new version this is not the case any more.

**Comment by mig-25** [comment]
Thanks, that worked out :)
